# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FacebookLiveReaction' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTBlob',
    'RCTImage',
    'RCTNetwork',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTText',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTPushNotification',
    'RCTActionSheet',
    'RCTGeolocation'
  ]
  
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'



  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end
